// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  related_products: dynamic(() => import("./RelatedProducts")),
  rich_text: dynamic(() => import("./RichText")),
};
